name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  gen-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Generate Keystore
        run: |
          mkdir -p app
          keytool -genkey -v \
            -keystore app/my-release-key.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias apkkey \
            -storepass lolrabimi \
            -keypass lolrab1mi \
            -dname "CN=Rabimi, OU=Dev, O=Rab1mi, L=Secert, ST=Secert, C=JP"
      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: my-release-key
          path: app/my-release-key.jks
